reorder_imports = true
condense_wildcard_suffixes = true
imports_granularity = "Crate"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
max_width = 160
comment_width = 160
